### ISSUE TITLE
【求助】关于argus-distribution如何在Windows上编译

### ISSUE THREAD

**Issue by Yang-0025** [wxntech/wxntech.github.io#1]
你好，我是北京邮电大学的一名研究生，我最近在做关于布料模拟和纸张模拟的研究，读论文发现的这个模拟器但是在Linux系统上编译的时候实在太难了，作为新手很多错误不知道怎么改，我想问您如何在Windows上编译它？跪求帮助。谢谢。

**Comment by wxntech** [comment]
你好。Linux上的编译作者提供了一键安装脚本。就是主目录下的install.sh，直接在目录下运行该脚本即可。
